#!/bin/bash
# $Header $
#
# This code is part of LDAP Account Manager (http://www.sourceforge.net/projects/lam)

# This script is run to update the existing Spanish translations in messages.po

./make_po
msgmerge -v ../../locale/es_ES/LC_MESSAGES/messages.po messages.po -o messages.po
