<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

use App\Classes\LDAP\SSSDPassword;

class SSSDPasswordTest extends TestCase
{
    /**
     * Fixture generated by the real sss_obfuscate(8) tool, confirming our format is byte
     * compatible with SSSD's own implementation, not just a self consistent round trip.
     */
    public function test_deobfuscate_matches_real_sss_obfuscate_output(): void
    {
        $token = 'AAAQABagVAjf9KgUyIxTw3A+HUfbig7N1+L0qtY4xAULt2GYHFc1B3CBWGAE9ArooklBkpxQtROiyCGDQH+VzLHYmiIAAQID';

        $this->assertEquals('Passw0rd',SSSDPassword::deobfuscate($token));
    }

    public function test_obfuscate_then_deobfuscate_round_trips(): void
    {
        $password = 'S0m3 \'Weird\' P@ssw0rd!';

        $this->assertEquals($password,SSSDPassword::deobfuscate(SSSDPassword::obfuscate($password)));
    }

    public function test_obfuscate_output_is_not_deterministic(): void
    {
        $password = 'Passw0rd';

        $this->assertNotEquals(SSSDPassword::obfuscate($password),SSSDPassword::obfuscate($password));
    }

    public function test_deobfuscate_rejects_invalid_base64(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        SSSDPassword::deobfuscate('not-valid-base64!!!');
    }

    public function test_deobfuscate_rejects_corrupt_buffer(): void
    {
        $buffer = base64_decode(SSSDPassword::obfuscate('Passw0rd'));

        $this->expectException(\InvalidArgumentException::class);

        SSSDPassword::deobfuscate(base64_encode($buffer.'x'));
    }
}
